default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: superman16779439
  host: localhost
  port: 5432

development:
  <<: *default
  database: tiktok_shop_analytics_development

test:
  <<: *default
  database: tiktok_shop_analytics_test

production:
  <<: *default
  database: tiktok_shop_analytics_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>